$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        500:{
            items:2
        },
        700:{
            items:4
        },
        850:{
            items:5
        },
        1000:{
            items:6
        }
    }
})